# https://learn.microsoft.com/es-mx/visualstudio/containers/tutorial-multicontainer?view=visualstudio
# https://learn.microsoft.com/es-mx/visualstudio/containers/launch-profiles?view=visualstudio
version: "3.9"

services:
    db:
        image: mysql:latest
        container_name: indicador_chile_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example

    api:
        image: ${DOCKER_REGISTRY-}api
        container_name: indicador_chile_api
        restart: always
        depends_on:
            - db
        ports:
            - "1970:8080"
            - "1973:8081"
        healthcheck:
            test: curl --fail https://localhost:1973/api/SII/GetCurrencyList?CurrencyType=USD&Year=2025 || exit 1
            interval: 20s
            timeout: 20s
            retries: 5
        build:
            context: .
            dockerfile: API/Dockerfile
        environment:
            # Asp Net Core
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            # Time Zone
            - TZ=America/Santiago
            # Idioma
            - LANG=es_CL.UTF-8
            - LANGUAGE=es_CL:es
            - LC_ALL=es_CL.UTF-8
        volumes:
            # Configuración del almacenamiento persistente
            - '/path/to/host/uptime/:/app/data'
            # Microsoft
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    
    web:
        image: ${DOCKER_REGISTRY-}web
        container_name: indicador_chile_web
        restart: always
        depends_on:
            - api
        ports:
            - "1971:8080"
            - "1974:8081"
        build:
            context: .
            dockerfile: Web/Dockerfile
        environment:
            # Asp Net Core
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8080
            - ASPNETCORE_HTTPS_PORTS=8081
            # Time Zone
            - TZ=America/Santiago
            # Idioma
            - LANG=es_CL.UTF-8
            - LANGUAGE=es_CL:es
            - LC_ALL=es_CL.UTF-8
        volumes:
            # Configuración del almacenamiento persistente
            - '/path/to/host/uptime/:/app/data'
            # Microsoft
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro