name: Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-docker-image:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: API
            os: ubuntu-latest
            dockerfile: ./API/Dockerfile
            image_name: ${{ vars.IMAGE_NAME }}/api
          
          - project: Web
            os: ubuntu-latest
            dockerfile: ./Web/Dockerfile
            image_name: ${{ vars.IMAGE_NAME }}/web

    container:
      image: ${{ matrix.dockerfile }}
      env:
        TZ: America/Santiago
    
    steps:
    - name: Checkout code
      id: checkoutCode
      uses: actions/checkout@v4 # Obtiene el código de tu repositorio

    - name: Log in to GitHub Container Registry
      id: logInGitHub
      uses: docker/login-action@v4 # Permite iniciar sesión en el registro de contenedores
      with:
        registry: ghcr.io # Usa el registro de contenedores de GitHub
        username: ${{ github.actor }} # Usa tu nombre de usuario de GitHub
        password: ${{ secrets.DOCKER_TOKEN }} # Usa el token de acceso personal guardado como secreto

    - name: Build and push Docker image
      id: buildPushImage
      uses: docker/build-push-action@v7 # Acción para construir y subir imágenes de Docker
      with:
        context: . # Construye desde el directorio raíz del proyecto
        file: ${{ matrix.dockerfile }}
        push: true # Sube la imagen al registro después de construirla
        tags: | # Asigna etiquetas a la imagen
          ghcr.io/${{ matrix.image_name }}:${{ github.sha }}
          ghcr.io/${{ matrix.image_name }}:latest
