name: docker compose override

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Crear el archivo docker-compose.override.yaml dinámicamente
    - name: Create docker-compose.override.yaml
      run: |
        cat << 'EOF' > docker-compose.override.yaml
        version: '3.9'

        services:
          api:
            environment:
              # Ports
              - ASPNETCORE_HTTP_PORTS=8080
              - ASPNETCORE_HTTPS_PORTS=8081
            volumes:
              # Microsoft
              - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          web:
            environment:
              # Ports
              - ASPNETCORE_HTTP_PORTS=8080
              - ASPNETCORE_HTTPS_PORTS=8081
            volumes:
              # Microsoft
              - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
              - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
          EOF

    # 3. Verificar que el archivo se creó correctamente (Opcional)
    - name: Verify file content
      run: cat docker-compose.override.yaml
