name: Build and deploy kubernetes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  build-and-deploy-kubernetes:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Solo si el primero fue exitoso

    strategy:
      fail-fast: false
      matrix:
        include:
          - project: API
            image_name: ${{ vars.IMAGE_NAME }}/api
          - project: Web
            image_name: ${{ vars.IMAGE_NAME }}/web

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout code
        id: checkoutCode
        uses: actions/checkout@v4 # Obtiene el código de tu repositorio
      
      # 2. Instalar kubectl en el entorno virtual
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      
      # 3. Configurar el archivo de acceso a Kubernetes descodificando el secreto
      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
      
      # 4. Actualizar la etiqueta de la imagen y desplegar los manifiestos
      - name: Deploy to Kubernetes Cluster
        run: |
          # Reemplazar dinámicamente la imagen en tus manifiestos con el tag del commit actual
          sed -i "s|image: .*|image: ghcr.io/${{ matrix.image_name }}:${{ github.sha }}|g" k8s/deployment.yaml
          
          # Aplicar los cambios en el clúster
          kubectl apply -f k8s/
          
          # Verificar que el despliegue termine correctamente
          kubectl rollout status deployment/mi-deployment-name -n default
